import { getAlerts, getDaemonStatus, getRecentActions, getPolicies, getTools, markAlertRead, interceptAction, createPolicy } from '../../services/securityApi.js';

const escapeHtml = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
const shell = (eyebrow, title, description) => `<section class="flex flex-col gap-2 pb-3 border-b border-outline-variant/30"><span class="font-label-caps text-primary">${eyebrow}</span><h1 class="font-headline-lg text-on-surface font-extrabold">${title}</h1><p class="font-body-sm text-on-surface-variant">${description}</p></section>`;
const card = (content, extra = '') => `<div class="tactical-card p-3.5 ${extra}">${content}</div>`;

export async function createSecurityCenterView(toast) {
  const container = document.createElement('div');
  container.className = 'flex flex-col gap-3';
  container.innerHTML = `${shell('MEMBER 2 // SECURITY OPERATIONS', 'SECURITY THREAT CENTER', 'Live policy enforcement, alert triage, and action decisions from the Sentinel daemon.')}<div class="font-code-sm text-outline">Loading daemon telemetry...</div>`;
  try {
    const [status, actions, alerts] = await Promise.all([getDaemonStatus(), getRecentActions(), getAlerts()]);
    const blocked = actions.filter((item) => item.outcome.includes('BLOCK')).length;
    const average = actions.length ? Math.round(actions.reduce((sum, item) => sum + item.risk_score, 0) / actions.length) : 0;
    container.innerHTML = `${shell('MEMBER 2 // SECURITY OPERATIONS', 'SECURITY THREAT CENTER', 'Live policy enforcement, alert triage, and action decisions from the Sentinel daemon.')}
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">${[
        ['DAEMON', status.running ? 'ONLINE' : 'OFFLINE', 'emerald'], ['ACTIONS', actions.length, 'primary'], ['BLOCKED', blocked, 'error'], ['AVG RISK', average, 'tertiary']
      ].map(([label, value, color]) => card(`<span class="font-label-caps text-outline">${label}</span><strong class="font-display-lg text-${color}">${value}</strong><span class="font-code-sm text-outline">Circuit: ${escapeHtml(status.circuit_breaker_state)}</span>`)).join('')}</div>
      <div class="grid grid-cols-1 lg:grid-cols-12 gap-3">
        ${card(`<div class="flex items-center justify-between pb-2 border-b border-outline-variant/30"><span class="font-headline-sm font-bold">UNREAD ALERTS</span><span class="badge-critical">${alerts.length}</span></div><div class="flex flex-col gap-2 mt-2">${alerts.length ? alerts.map((alert) => `<div class="p-2 rounded bg-surface-low flex items-start justify-between gap-2"><div><span class="font-label-caps text-tertiary">${escapeHtml(alert.severity)}</span><div class="font-body-sm text-on-surface font-bold">${escapeHtml(alert.title)}</div><div class="font-code-sm text-outline">${escapeHtml(alert.description)}</div></div><button class="btn-secondary alert-read" data-id="${alert.id}">READ</button></div>`).join('') : '<span class="font-code-sm text-outline">No unread alerts.</span>'}</div>`, 'lg:col-span-7')}
        ${card(`<span class="font-label-caps text-outline">RUNTIME HEALTH</span><div class="flex flex-col gap-2 mt-2"><div class="flex justify-between"><span>Policy engine</span><strong class="text-emerald">ACTIVE</strong></div><div class="flex justify-between"><span>Active session</span><strong class="text-primary">${status.active_session_id ? '1' : 'NONE'}</strong></div><div class="flex justify-between"><span>Daemon version</span><strong class="text-on-surface">${escapeHtml(status.version)}</strong></div></div>`, 'lg:col-span-5')}</div>
      ${card(`<div class="flex items-center justify-between pb-2 border-b border-outline-variant/30"><span class="font-headline-sm font-bold">REQUEST TESTER</span><span class="font-label-caps text-error">NO FILE EXECUTION</span></div><form id="security-request-form" class="grid grid-cols-1 md:grid-cols-12 gap-2 mt-2"><input name="path" required value="~/.ssh/id_rsa" class="md:col-span-6 bg-surface-high border border-outline-variant p-2 font-code-sm"/><select name="operation" class="md:col-span-3 bg-surface-high border border-outline-variant p-2 font-code-sm"><option>DELETE</option><option>READ</option><option>WRITE</option></select><button class="btn-danger md:col-span-3">EVALUATE</button></form><div id="security-result" class="font-code-sm text-outline mt-2"></div>`)}
      ${card(`<div class="flex items-center justify-between pb-2 border-b border-outline-variant/30"><span class="font-headline-sm font-bold">RECENT DECISIONS</span><span class="font-label-caps text-primary">FLIGHT RECORDER</span></div><div class="overflow-x-auto mt-2"><table class="w-full text-left font-code-sm"><thead class="text-outline"><tr><th>Action</th><th>Target</th><th>Outcome</th><th>Risk</th></tr></thead><tbody>${actions.map((item) => `<tr class="border-t border-outline-variant/20"><td class="py-2">${escapeHtml(item.action_type)}</td><td>${escapeHtml(item.target_path || 'N/A')}</td><td class="${item.outcome.includes('BLOCK') ? 'text-error' : 'text-emerald'}">${escapeHtml(item.outcome)}</td><td class="text-tertiary">${item.risk_score}</td></tr>`).join('')}</tbody></table></div>`)}
    `;
    container.querySelectorAll('.alert-read').forEach((button) => button.addEventListener('click', async () => { await markAlertRead(button.dataset.id); button.closest('.p-2').remove(); toast.show('Alert marked as read.', 'success'); }));
    container.querySelector('#security-request-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await interceptAction({ agent_id: 'member2-portal', agent_type: 'SHELL', action_type: `FILE_${form.get('operation')}`, operation: form.get('operation'), target_path: form.get('path'), command: 'portal request tester' }); const output = container.querySelector('#security-result'); output.textContent = `${result.decision} // RISK ${result.risk_score} // ${result.reason_code}: ${result.explanation}`; output.className = `font-code-sm mt-2 ${result.decision === 'BLOCK' ? 'text-error' : 'text-emerald'}`; });
  } catch (error) { container.innerHTML += card(`<span class="text-error font-code-sm">Daemon unavailable on port 8765. Start the backend to load live security telemetry.</span>`); }
  return container;
}

export async function createPoliciesView(toast) {
  const container = document.createElement('div'); container.className = 'flex flex-col gap-3'; container.innerHTML = `${shell('MEMBER 2 // POLICY ENGINE', 'SECURITY POLICIES', 'TOML-backed policy rules evaluated before agent actions execute.')}<span class="font-code-sm text-outline">Loading policies...</span>`;
  try { const policies = await getPolicies(); container.innerHTML = `${shell('MEMBER 2 // POLICY ENGINE', 'SECURITY POLICIES', 'TOML-backed policy rules evaluated before agent actions execute.')}<div class="flex justify-end"><button id="new-policy" class="btn-primary">+ CREATE POLICY</button></div>${policies.map((policy) => card(`<div class="flex items-center justify-between"><div><h3 class="font-headline-sm font-bold">${escapeHtml(policy.name)}</h3><span class="font-code-sm text-outline">Scope: ${escapeHtml(policy.scope)}</span></div><span class="badge-${policy.action === 'DENY' ? 'critical' : 'high'}">${escapeHtml(policy.action)}</span></div>`)).join('')}`; container.querySelector('#new-policy').addEventListener('click', () => toast.show('Policy creation is available from the policy route.', 'info')); } catch { container.innerHTML += card('<span class="text-error font-code-sm">Daemon unavailable. Policies could not be loaded.</span>'); } return container;
}

export async function createToolsView() { const container = document.createElement('div'); container.className = 'flex flex-col gap-3'; container.innerHTML = `${shell('MEMBER 2 // MANIFEST REGISTRY', 'SYSTEM TOOLS', 'Registered capabilities loaded from the daemon manifest directory.')}<span class="font-code-sm text-outline">Loading tools...</span>`; try { const tools = await getTools(); container.innerHTML = `${shell('MEMBER 2 // MANIFEST REGISTRY', 'SYSTEM TOOLS', 'Registered capabilities loaded from the daemon manifest directory.')}<div class="grid grid-cols-1 md:grid-cols-2 gap-3">${tools.map((tool) => card(`<span class="font-headline-sm font-bold text-primary">${escapeHtml(tool.name)}</span><span class="font-code-sm text-outline">Owner: ${escapeHtml(tool.owner)}</span><span class="badge-emerald">${escapeHtml(tool.status)}</span>`)).join('')}</div>`; } catch { container.innerHTML += card('<span class="text-error font-code-sm">Daemon unavailable. Tools could not be loaded.</span>'); } return container; }

export async function createAuditView() { const container = document.createElement('div'); container.className = 'flex flex-col gap-3'; container.innerHTML = `${shell('MEMBER 2 // APPEND-ONLY RECORDER', 'AUDIT LOGS', 'Every intercepted action, decision, and risk score recorded by SentinelAI.')}<span class="font-code-sm text-outline">Loading audit events...</span>`; try { const actions = await getRecentActions(50); container.innerHTML = `${shell('MEMBER 2 // APPEND-ONLY RECORDER', 'AUDIT LOGS', 'Every intercepted action, decision, and risk score recorded by SentinelAI.')} ${card(`<div class="overflow-x-auto"><table class="w-full text-left font-code-sm"><thead class="text-outline"><tr><th>Time</th><th>Action</th><th>Target</th><th>Outcome</th><th>Risk</th></tr></thead><tbody>${actions.map((item) => `<tr class="border-t border-outline-variant/20"><td class="py-2">${new Date(item.created_at).toLocaleTimeString()}</td><td>${escapeHtml(item.action_type)}</td><td>${escapeHtml(item.target_path || 'N/A')}</td><td class="${item.outcome.includes('BLOCK') ? 'text-error' : 'text-emerald'}">${escapeHtml(item.outcome)}</td><td class="text-tertiary">${item.risk_score}</td></tr>`).join('')}</tbody></table></div>`)}`; } catch { container.innerHTML += card('<span class="text-error font-code-sm">Daemon unavailable. Audit events could not be loaded.</span>'); } return container; }
